// SPDX-FileCopyrightText: 2026 Padparadscho <contact@padparadscho.com>
// SPDX-License-Identifier: AGPL-3.0-only

/** This file was generated by kysely-codegen. Please do not edit it manually. */

import type { ColumnType } from "kysely";

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
	[x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Actions {
	action_created_at: Generated<Timestamp>;
	action_id: Generated<number>;
	action_meta: Json | null;
	action_target: string | null;
	action_type: string;
	actor_address: string;
}

export interface AuthChallenges {
	challenge_expires_at: Timestamp;
	challenge_id: Generated<string>;
	challenge_nonce: string;
	is_used: Generated<boolean>;
	user_address: string;
}

export interface Badges {
	badge_id: Generated<number>;
	badge_name: string;
	badge_slug: string;
	is_auto: Generated<boolean>;
}

export interface Categories {
	category_id: Generated<number>;
	category_name: string;
	category_section: string;
	category_slug: string;
	min_role_to_post: string;
}

export interface Comments {
	comment_body: string;
	comment_created_at: Generated<Timestamp>;
	comment_edited_at: Timestamp | null;
	comment_id: Generated<number>;
	comment_removed_at: Timestamp | null;
	parent_id: number | null;
	post_id: number;
	user_address: string;
}

export interface Events {
	event_created_by: string;
	event_description: string | null;
	event_ends_at: Timestamp;
	event_id: Generated<number>;
	event_starts_at: Timestamp;
	event_title: string;
}

export interface Points {
	point_amount: number;
	point_created_at: Generated<Timestamp>;
	point_granted_by: string | null;
	point_id: Generated<number>;
	point_reason: string;
	user_address: string;
}

export interface Posts {
	category_id: number;
	is_locked: Generated<boolean>;
	is_pinned: Generated<boolean>;
	post_created_at: Generated<Timestamp>;
	post_id: Generated<number>;
	post_title: string;
	user_address: string;
}

export interface PostTags {
	post_id: number;
	tag_id: number;
}

export interface Reports {
	report_created_at: Generated<Timestamp>;
	report_id: Generated<number>;
	report_reason: string;
	report_reviewed_at: Timestamp | null;
	report_reviewed_by: string | null;
	report_status: Generated<string>;
	reported_content_id: number;
	reported_content_type: string;
	reporter_address: string;
}

export interface Tags {
	is_auto: Generated<boolean>;
	min_role_to_assign: string;
	tag_id: Generated<number>;
	tag_name: string;
	tag_slug: string;
}

export interface Upvotes {
	upvote_created_at: Generated<Timestamp>;
	upvote_id: number;
	upvote_type: string;
	user_address: string;
}

export interface UserBadges {
	badge_granted_at: Generated<Timestamp>;
	badge_granted_by: string | null;
	badge_id: number;
	user_address: string;
}

export interface Users {
	user_address: string;
	user_banned_at: Timestamp | null;
	user_created_at: Generated<Timestamp>;
	user_points: Generated<number>;
	user_role: Generated<string>;
}

export interface Whitelist {
	address: string;
	address_added_at: Generated<Timestamp>;
	address_removed_at: Timestamp | null;
}

export interface DB {
	actions: Actions;
	auth_challenges: AuthChallenges;
	badges: Badges;
	categories: Categories;
	comments: Comments;
	events: Events;
	points: Points;
	post_tags: PostTags;
	posts: Posts;
	reports: Reports;
	tags: Tags;
	upvotes: Upvotes;
	user_badges: UserBadges;
	users: Users;
	whitelist: Whitelist;
}
